version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pswd
  dba:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      PMA_USER: root
      PMA_PASSWORD: pswd
  www:
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/wp-support-check"
    ports:
    - 80:80
    - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pswd
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', true );